/**
 * 판매자가 상품·이미지·타임딜·재고·픽업·문의·fulfillment를 실제 API로 운영하는 화면입니다.
 * 모든 패널은 로딩·빈 상태·오류·성공 피드백과 mutation 중 중복 실행 방지를 제공합니다.
 */
import { ImageUp, LoaderCircle, PackageCheck, RefreshCw, Send, TrendingUp } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useLocation } from "react-router-dom";
import { DashboardShell } from "@/shared/layout/DashboardShell";
import { StatusBadge } from "@/shared/components/StatusBadge";
import { adjustInventory, createSellerDeal, createSellerProduct, endSellerDeal, getInventoryHistory, getProductUploadUrl, getSellerDashboard, getSellerDeals, getSellerFulfillments, getSellerInquiries, getSellerPickupLocations, getSellerPickupSlots, getSellerProducts, hideSellerProduct, replySellerInquiry, submitSellerProduct, updateFulfillmentStatus, updateSellerDeal, updateSellerProduct, uploadProductImage, type Fulfillment, type Inquiry, type RawRecord } from "@/lib/api";
import { formatPrice } from "@/shared/catalog";

const info: Record<string, [string, string]> = {
  "/seller": ["판매자 대시보드", "상품·fulfillment·문의와 예약 금액을 실시간 집계합니다."], "/seller/products": ["상품 관리", "상품을 수정·숨김·검수 요청하고 이미지와 재고를 관리합니다."], "/seller/products/new": ["상품 등록", "운영 상품 정보를 초안으로 등록합니다."], "/seller/orders": ["주문 현황", "판매자별 fulfillment를 정방향으로 처리합니다."], "/seller/analytics": ["딜·통계·픽업", "타임딜과 픽업 장소·슬롯 운영 상태를 확인합니다."], "/seller/inquiries": ["판매자 문의", "배정된 고객 문의 대화를 확인하고 답변합니다."],
};
const str = (item: RawRecord, key: string) => String(item[key] ?? ""); const num = (item: RawRecord, key: string) => Number(item[key] ?? 0);
const date = (input?: string) => input ? new Date(input).toLocaleString("ko-KR", { dateStyle: "medium", timeStyle: "short" }) : "-";
const statusLabel: Record<string, string> = { pending: "접수", confirmed: "확인", ready: "픽업 준비", completed: "완료", cancelled: "취소", draft: "초안", pending_review: "검수 중", active: "운영", rejected: "반려", hidden: "숨김", ended: "종료" };
const nextStatus: Record<string, "confirmed" | "ready" | "completed" | undefined> = { pending: "confirmed", confirmed: "ready", ready: "completed" };

function Feedback({ error, notice }: { error: string | null; notice: string | null }) { return <>{notice && <div className="order-notice" role="status">{notice}</div>}{error && <div className="order-error" role="alert">{error}</div>}</>; }
function Loading({ text }: { text: string }) { return <div className="order-loading"><LoaderCircle className="spin-icon" /> {text}</div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty-state compact-empty"><PackageCheck size={30} /><h3>{title}</h3><p>{text}</p></div>; }

function DashboardPanel() {
  const [data, setData] = useState<Record<string, number | Record<string, number>> | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; void getSellerDashboard().then((result) => { if (!active) return; if (result.ok) setData(result.data?.dashboard ?? null); else setError(result.error?.message ?? "운영 현황을 불러오지 못했습니다."); }); return () => { active = false; }; }, []);
  if (!data && !error) return <Loading text="판매자 운영 지표를 집계하는 중입니다." />;
  const metrics: Array<[string, string | number]> = [["등록 상품", Number(data?.productCount ?? 0)], ["fulfillment", Number(data?.fulfillmentCount ?? 0)], ["예약 금액", formatPrice(Number(data?.grossReservedAmount ?? 0))], ["답변 대기 문의", Number(data?.openInquiryCount ?? 0)]];
  return <><Feedback error={error} notice={null} /><div className="metric-grid">{metrics.map(([label, value]) => <article key={String(label)}><span><TrendingUp /></span><p>{label}</p><strong>{value ?? 0}</strong></article>)}</div><section className="dashboard-panel"><div className="panel-title-row"><div><p>FULFILLMENT STATUS</p><h2>처리 단계</h2></div><StatusBadge type="live">Supabase 집계</StatusBadge></div><div className="operation-grid">{Object.entries((data?.fulfillmentStatus ?? {}) as Record<string, number>).map(([key, value]) => <article key={key}><span>{statusLabel[key] ?? key}</span><strong>{value}</strong></article>)}</div></section></>;
}

function ProductForm({ onSaved }: { onSaved?: () => void }) {
  const [form, setForm] = useState({ name: "", description: "", category: "", image: "products/default.webp", regularPrice: 0, inventory: 0 }); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); const result = await createSellerProduct(form); setBusy(false); if (!result.ok) return setError(result.error?.message ?? "상품을 등록하지 못했습니다."); setNotice("상품 초안을 등록했습니다. 상품 관리에서 이미지를 올리고 검수를 요청하세요."); setForm({ name: "", description: "", category: "", image: "products/default.webp", regularPrice: 0, inventory: 0 }); onSaved?.(); };
  return <section className="dashboard-panel"><div className="panel-title-row"><div><p>NEW PRODUCT</p><h2>상품 초안 등록</h2></div><StatusBadge type="live">저장 API</StatusBadge></div><Feedback error={error} notice={notice} /><form className="operation-form" onSubmit={submit}><label>상품명<input required minLength={2} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>카테고리<input required value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} /></label><label>정상가<input required min={0} type="number" value={form.regularPrice} onChange={(event) => setForm({ ...form, regularPrice: Number(event.target.value) })} /></label><label>초기 재고<input required min={0} type="number" value={form.inventory} onChange={(event) => setForm({ ...form, inventory: Number(event.target.value) })} /></label><label className="wide">설명<textarea required minLength={2} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><button className="primary-button" disabled={busy}>{busy && <LoaderCircle className="spin-icon" size={16} />}상품 등록</button></form></section>;
}

function ProductsPanel() {
  const [items, setItems] = useState<RawRecord[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [history, setHistory] = useState<Record<string, RawRecord[]>>({});
  const load = useCallback(async () => { setLoading(true); const result = await getSellerProducts(); setLoading(false); if (result.ok) setItems(result.data?.products ?? []); else setError(result.error?.message ?? "상품을 불러오지 못했습니다."); }, []);
  useEffect(() => { void load(); }, [load]);
  const action = async (id: string, kind: "save" | "submit" | "hide" | "inventory", payload?: RawRecord) => { setBusy(id + kind); setError(null); setNotice(null); const current = items.find((item) => item.id === id)!; const result = kind === "save" ? await updateSellerProduct(id, { name: str(current, "name"), description: str(current, "description"), category: str(current, "category"), regularPrice: num(current, "regular_price"), inventory: num(current, "inventory"), image: str(current, "image_path") || str(current, "image") }) : kind === "submit" ? await submitSellerProduct(id) : kind === "hide" ? await hideSellerProduct(id) : await adjustInventory(id, Number(payload?.delta), String(payload?.reason) as "manual" | "restock"); setBusy(null); if (!result.ok) return setError(result.error?.message ?? "요청을 처리하지 못했습니다."); setNotice(kind === "inventory" ? "재고와 재고 원장을 갱신했습니다." : "상품 상태를 갱신했습니다."); await load(); };
  const upload = async (id: string, file: File) => { setBusy(id + "upload"); setError(null); const signed = await getProductUploadUrl(id, file); if (!signed.ok || !signed.data) { setBusy(null); return setError(signed.error?.message ?? "업로드 URL을 만들지 못했습니다."); } const uploaded = await uploadProductImage(signed.data.bucket, signed.data.objectPath, signed.data.token, file); if (!uploaded.ok) { setBusy(null); return setError("Storage 이미지 업로드에 실패했습니다."); } const saved = await updateSellerProduct(id, { image: signed.data.objectPath }); setBusy(null); if (!saved.ok) return setError(saved.error?.message ?? "이미지 경로를 저장하지 못했습니다."); setNotice("상품 이미지를 업로드했습니다."); await load(); };
  const showHistory = async (id: string) => { const result = await getInventoryHistory(id); if (!result.ok) return setError(result.error?.message ?? "재고 이력을 불러오지 못했습니다."); setHistory((current) => ({ ...current, [id]: result.data?.movements ?? [] })); };
  if (loading) return <Loading text="상품 목록을 불러오는 중입니다." />;
  return <section className="dashboard-panel"><div className="panel-title-row"><div><p>PRODUCT OPERATIONS</p><h2>등록 상품</h2></div><button className="secondary-button" onClick={() => void load()}><RefreshCw size={15} /> 새로고침</button></div><Feedback error={error} notice={notice} />{items.length === 0 ? <Empty title="등록 상품이 없습니다." text="상품 등록 메뉴에서 첫 상품을 추가하세요." /> : <div className="operation-list">{items.map((item) => <article className="operation-card" key={str(item, "id")}><header><div><strong>{str(item, "name")}</strong><small>{str(item, "category")} · 재고 {num(item, "inventory")}</small></div><StatusBadge type={str(item, "status") === "active" ? "live" : "ready"}>{statusLabel[str(item, "status")] ?? str(item, "status")}</StatusBadge></header><div className="operation-form compact"><label>상품명<input value={str(item, "name")} onChange={(event) => setItems((list) => list.map((row) => row.id === item.id ? { ...row, name: event.target.value } : row))} /></label><label>정상가<input type="number" value={num(item, "regular_price")} onChange={(event) => setItems((list) => list.map((row) => row.id === item.id ? { ...row, regular_price: Number(event.target.value) } : row))} /></label><label className="wide">설명<textarea value={str(item, "description")} onChange={(event) => setItems((list) => list.map((row) => row.id === item.id ? { ...row, description: event.target.value } : row))} /></label></div><div className="action-row"><button onClick={() => void action(str(item, "id"), "save")} disabled={busy !== null}>수정 저장</button>{["draft", "rejected"].includes(str(item, "status")) && <button onClick={() => void action(str(item, "id"), "submit")} disabled={busy !== null}>검수 요청</button>}{["active", "pending_review"].includes(str(item, "status")) && <button onClick={() => void action(str(item, "id"), "hide")} disabled={busy !== null}>상품 숨김</button>}<label className="file-action"><ImageUp size={15} /> 이미지 업로드<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(str(item, "id"), file); }} /></label><button onClick={() => { const delta = Number(window.prompt("재고 증감 수량을 입력하세요. 예: 10 또는 -3")); if (delta) void action(str(item, "id"), "inventory", { delta, reason: delta > 0 ? "restock" : "manual" }); }} disabled={busy !== null}>재고 조정</button><button onClick={() => void showHistory(str(item, "id"))}>재고 이력</button></div>{history[str(item, "id")] && <div className="history-list">{history[str(item, "id")].length === 0 ? <small>기록이 없습니다.</small> : history[str(item, "id")].map((movement) => <span key={str(movement, "id")}>{date(str(movement, "created_at"))} · {str(movement, "reason")} · {num(movement, "quantity_delta") > 0 ? "+" : ""}{num(movement, "quantity_delta")}</span>)}</div>}</article>)}</div>}</section>;
}

function FulfillmentsPanel() {
  const [items, setItems] = useState<Fulfillment[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); const result = await getSellerFulfillments(); setLoading(false); if (result.ok) setItems(result.data?.fulfillments ?? []); else setError(result.error?.message ?? "fulfillment를 불러오지 못했습니다."); }, []); useEffect(() => { void load(); }, [load]);
  const advance = async (item: Fulfillment) => { const next = nextStatus[item.status]; if (!next) return; setBusy(item.id); const result = await updateFulfillmentStatus(item.id, next); setBusy(null); if (!result.ok) return setError(result.error?.message ?? "상태를 변경하지 못했습니다."); setNotice(`${item.orderNumber} 처리를 ${statusLabel[next]} 단계로 변경했습니다.`); await load(); };
  if (loading) return <Loading text="판매자별 fulfillment를 불러오는 중입니다." />;
  return <section className="dashboard-panel"><div className="panel-title-row"><div><p>FULFILLMENT</p><h2>판매자 처리 목록</h2></div><StatusBadge type="live">최소 정보 DTO</StatusBadge></div><Feedback error={error} notice={notice} />{items.length === 0 ? <Empty title="처리할 주문이 없습니다." text="담당 상품 주문이 접수되면 표시됩니다." /> : <div className="operation-list">{items.map((item) => <article className="seller-order-row" key={item.id}><div className="seller-order-main"><span>{item.orderNumber}</span><strong>{item.items.map((row) => `${row.productName} × ${row.quantity}`).join(", ")}</strong><small>{date(item.createdAt)} · {formatPrice(item.subtotal)} · 장소 {item.pickupLocationId}</small></div><div className="seller-order-meta"><StatusBadge type={item.status === "completed" ? "live" : "ready"}>{statusLabel[item.status]}</StatusBadge><small>픽업 {item.pickupStatus}</small></div>{nextStatus[item.status] && <button className="secondary-button" disabled={busy === item.id} onClick={() => void advance(item)}>{busy === item.id && <LoaderCircle className="spin-icon" size={15} />}{statusLabel[nextStatus[item.status]!]}로 변경</button>}</article>)}</div>}</section>;
}

function DealsPanel() {
  const [products, setProducts] = useState<RawRecord[]>([]); const [deals, setDeals] = useState<RawRecord[]>([]); const [locations, setLocations] = useState<Array<{ id: string; name: string; address: string }>>([]); const [slots, setSlots] = useState<Array<{ id: string; pickupDate: string; startTime: string; endTime: string; capacity: number; reservedCount: number }>>([]); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [form, setForm] = useState({ productId: "", dealPrice: 0, target: 1, startsAt: "", endsAt: "" });
  const load = useCallback(async () => { const [productResult, dealResult, locationResult, slotResult] = await Promise.all([getSellerProducts(), getSellerDeals(), getSellerPickupLocations(), getSellerPickupSlots()]); if (!productResult.ok || !dealResult.ok || !locationResult.ok || !slotResult.ok) return setError("딜 또는 픽업 운영 정보를 불러오지 못했습니다."); setProducts(productResult.data?.products ?? []); setDeals(dealResult.data?.deals ?? []); setLocations(locationResult.data?.locations ?? []); setSlots(slotResult.data?.slots ?? []); }, []); useEffect(() => { void load(); }, [load]);
  const create = async (event: FormEvent) => { event.preventDefault(); setBusy(true); const result = await createSellerDeal({ ...form, startsAt: new Date(form.startsAt).toISOString(), endsAt: new Date(form.endsAt).toISOString() }); setBusy(false); if (!result.ok) return setError(result.error?.message ?? "딜을 만들지 못했습니다."); setNotice("딜 초안을 만들었습니다."); await load(); };
  const end = async (id: string) => { if (!window.confirm("이 딜을 종료할까요?")) return; const result = await endSellerDeal(id); if (!result.ok) return setError(result.error?.message ?? "딜을 종료하지 못했습니다."); setNotice("딜 운영을 종료했습니다."); await load(); };
  return <><Feedback error={error} notice={notice} /><section className="dashboard-panel"><div className="panel-title-row"><div><p>TIME DEALS</p><h2>타임딜 생성·수정·종료</h2></div><StatusBadge type="live">딜 API</StatusBadge></div><form className="operation-form" onSubmit={create}><label>상품<select required value={form.productId} onChange={(event) => setForm({ ...form, productId: event.target.value })}><option value="">활성 상품 선택</option>{products.filter((item) => item.status === "active").map((item) => <option value={str(item, "id")} key={str(item, "id")}>{str(item, "name")}</option>)}</select></label><label>딜 가격<input required min={0} type="number" value={form.dealPrice} onChange={(event) => setForm({ ...form, dealPrice: Number(event.target.value) })} /></label><label>목표 수량<input required min={1} type="number" value={form.target} onChange={(event) => setForm({ ...form, target: Number(event.target.value) })} /></label><label>시작<input required type="datetime-local" value={form.startsAt} onChange={(event) => setForm({ ...form, startsAt: event.target.value })} /></label><label>종료<input required type="datetime-local" value={form.endsAt} onChange={(event) => setForm({ ...form, endsAt: event.target.value })} /></label><button className="primary-button" disabled={busy}>딜 만들기</button></form><div className="operation-list">{deals.map((deal) => <article className="operation-card" key={str(deal, "id")}><header><div><strong>{str((deal.products ?? {}) as RawRecord, "name") || str(deal, "product_id")}</strong><small>{formatPrice(num(deal, "deal_price"))} · {num(deal, "participants")}/{num(deal, "target")}</small></div><StatusBadge type={str(deal, "status") === "active" ? "live" : "ready"}>{statusLabel[str(deal, "status")]}</StatusBadge></header><div className="action-row"><button onClick={() => { const price = Number(window.prompt("변경할 딜 가격", String(num(deal, "deal_price")))); if (price >= 0) void updateSellerDeal(str(deal, "id"), { dealPrice: price }).then(load); }}>가격 수정</button>{["draft", "active"].includes(str(deal, "status")) && <button onClick={() => void end(str(deal, "id"))}>딜 종료</button>}</div></article>)}</div></section><section className="dashboard-panel spaced-panel"><div className="panel-title-row"><div><p>PICKUP OPERATIONS</p><h2>판매자 픽업 조회</h2></div><StatusBadge type="live">관리자 운영 장소</StatusBadge></div><div className="operation-grid">{locations.map((location) => <article key={location.id}><strong>{location.name}</strong><small>{location.address}</small></article>)}</div><div className="operation-list">{slots.map((slot) => <article className="compact-row" key={slot.id}><span>{slot.pickupDate} {slot.startTime}–{slot.endTime}</span><strong>{slot.reservedCount}/{slot.capacity}명</strong></article>)}</div></section></>;
}

function InquiriesPanel() {
  const [items, setItems] = useState<Inquiry[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [replies, setReplies] = useState<Record<string, string>>({}); const [busy, setBusy] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); const result = await getSellerInquiries(); setLoading(false); if (result.ok) setItems(result.data?.inquiries ?? []); else setError(result.error?.message ?? "문의를 불러오지 못했습니다."); }, []); useEffect(() => { void load(); }, [load]);
  const reply = async (id: string) => { const message = replies[id]?.trim(); if (!message) return; setBusy(id); const result = await replySellerInquiry(id, message); setBusy(null); if (!result.ok) return setError(result.error?.message ?? "답변을 저장하지 못했습니다."); setReplies((current) => ({ ...current, [id]: "" })); setNotice("문의 답변을 저장했습니다."); await load(); };
  if (loading) return <Loading text="담당 문의를 불러오는 중입니다." />;
  return <section className="dashboard-panel"><div className="panel-title-row"><div><p>SELLER INQUIRIES</p><h2>배정 문의 대화</h2></div><StatusBadge type="live">담당 문의만 표시</StatusBadge></div><Feedback error={error} notice={notice} />{items.length === 0 ? <Empty title="담당 문의가 없습니다." text="상품 문의가 배정되면 표시됩니다." /> : <div className="conversation-list">{items.map((item) => <article key={item.id}><header><strong>{item.subject}</strong><StatusBadge type="ready">{item.status}</StatusBadge></header><div className="message-list">{(item.inquiry_messages ?? []).map((message) => <p key={message.id}><span>{message.message}</span><small>{date(message.created_at)}</small></p>)}</div><div className="reply-row"><textarea value={replies[item.id] ?? ""} onChange={(event) => setReplies({ ...replies, [item.id]: event.target.value })} aria-label={`${item.subject} 답변`} /><button className="primary-button" disabled={busy === item.id || !(replies[item.id]?.trim())} onClick={() => void reply(item.id)}><Send size={15} /> 답변</button></div></article>)}</div>}</section>;
}

export default function SellerPage() {
  const path = useLocation().pathname; const [title, description] = info[path] ?? info["/seller"];
  const panel = path === "/seller" ? <DashboardPanel /> : path === "/seller/products/new" ? <ProductForm /> : path === "/seller/products" ? <ProductsPanel /> : path === "/seller/orders" ? <FulfillmentsPanel /> : path === "/seller/analytics" ? <DealsPanel /> : <InquiriesPanel />;
  return <DashboardShell type="seller"><div className="dashboard-page-heading"><div><p>판매자 기능</p><h1>{title}</h1><span>{description}</span></div><StatusBadge type="live">운영 API 연결</StatusBadge></div><div className="dashboard-content">{panel}</div></DashboardShell>;
}
