/**
 * 관리자 통계·사용자·판매자 신청·상품·딜·픽업·moderation·감사 로그 API를 제공합니다.
 * 모든 변경은 admin 역할을 재검증하고 audit_logs에 actor와 변경 사유를 기록합니다.
 */
import { Hono } from "hono";
import { z } from "zod";
import { apiFailure, apiSuccess } from "../../http.js";
import { requireRole } from "../../middleware/auth.js";
import { getAdminSupabase } from "../../supabase.js";

export const adminRouter = new Hono();
const adminOnly = requireRole("admin");
const reasonSchema = z.string().min(2).max(500);
const audit = async (actorId: string, action: string, entityType: string, entityId: string, beforeData: unknown, afterData: unknown, reason: string) => getAdminSupabase().from("audit_logs").insert({ actor_id: actorId, action, entity_type: entityType, entity_id: entityId, before_data: beforeData, after_data: afterData, reason });

adminRouter.get("/admin-dashboard", adminOnly, async (context) => {
  const supabase = getAdminSupabase(); const tables = ["profiles", "products", "deals", "orders", "fulfillment_groups", "inquiries", "reviews", "community_reports"];
  const results = await Promise.all(tables.map((table) => supabase.from(table).select("*", { count: "exact", head: true })));
  const failed = results.find((result) => result.error); if (failed?.error) return context.json(apiFailure("QUERY_FAILED", "관리자 통계를 집계하지 못했습니다."), 502);
  return context.json(apiSuccess({ dashboard: Object.fromEntries(tables.map((table, index) => [table, results[index].count ?? 0])), generatedAt: new Date().toISOString() }));
});
adminRouter.get("/admin-users", adminOnly, async (context) => {
  const { data, error } = await getAdminSupabase().from("profiles").select("id,name,role,phone,preferred_region,is_suspended,created_at").order("created_at", { ascending: false }).limit(200);
  return error ? context.json(apiFailure("QUERY_FAILED", "사용자를 조회하지 못했습니다."), 502) : context.json(apiSuccess({ users: data ?? [] }));
});
adminRouter.patch("/admin-users/:id", adminOnly, async (context) => {
  const parsed = z.object({ role: z.enum(["user", "seller", "admin"]).optional(), isSuspended: z.boolean().optional(), reason: reasonSchema }).strict().safeParse(await context.req.json().catch(() => null));
  if (!parsed.success) return context.json(apiFailure("INVALID_INPUT", "변경 내용과 사유를 확인하세요."), 400);
  if (context.req.param("id") === context.var.currentUser!.id && (parsed.data.isSuspended || (parsed.data.role && parsed.data.role !== "admin"))) return context.json(apiFailure("SELF_LOCKOUT", "현재 관리자 자신의 권한을 제거하거나 정지할 수 없습니다."), 409);
  const supabase = getAdminSupabase(); const before = await supabase.from("profiles").select("id,role,is_suspended").eq("id", context.req.param("id")).maybeSingle(); if (!before.data) return context.json(apiFailure("NOT_FOUND", "사용자를 찾을 수 없습니다."), 404);
  const update = { ...(parsed.data.role ? { role: parsed.data.role } : {}), ...(parsed.data.isSuspended !== undefined ? { is_suspended: parsed.data.isSuspended } : {}), updated_at: new Date().toISOString() }; const { data, error } = await supabase.from("profiles").update(update).eq("id", context.req.param("id")).select().single();
  if (error) return context.json(apiFailure("SAVE_FAILED", "사용자를 변경하지 못했습니다."), 400); await audit(context.var.currentUser!.id, "user.update", "profile", data.id, before.data, data, parsed.data.reason); return context.json(apiSuccess({ user: data }));
});
adminRouter.get("/admin/seller-applications", adminOnly, async (context) => { const { data, error } = await getAdminSupabase().from("seller_applications").select("*,profiles(name)").order("created_at", { ascending: false }); return error ? context.json(apiFailure("QUERY_FAILED", "판매자 신청을 조회하지 못했습니다."), 502) : context.json(apiSuccess({ applications: data ?? [] })); });
adminRouter.patch("/admin/seller-applications/:id", adminOnly, async (context) => {
  const parsed = z.object({ status: z.enum(["approved", "rejected"]), reason: reasonSchema }).strict().safeParse(await context.req.json().catch(() => null)); if (!parsed.success) return context.json(apiFailure("INVALID_INPUT", "심사 결과를 확인하세요."), 400);
  const supabase = getAdminSupabase(); const before = await supabase.from("seller_applications").select("*").eq("id", context.req.param("id")).eq("status", "pending").maybeSingle(); if (!before.data) return context.json(apiFailure("NOT_FOUND", "대기 중인 신청을 찾을 수 없습니다."), 404);
  const { data, error } = await supabase.from("seller_applications").update({ status: parsed.data.status, review_reason: parsed.data.reason, reviewed_by: context.var.currentUser!.id, reviewed_at: new Date().toISOString() }).eq("id", before.data.id).select().single(); if (error) return context.json(apiFailure("SAVE_FAILED", "심사 결과를 저장하지 못했습니다."), 400);
  if (parsed.data.status === "approved") await supabase.from("profiles").update({ role: "seller", updated_at: new Date().toISOString() }).eq("id", before.data.user_id); await audit(context.var.currentUser!.id, "seller_application.review", "seller_application", data.id, before.data, data, parsed.data.reason); return context.json(apiSuccess({ application: data }));
});

for (const [path, table] of [["/admin/products", "products"], ["/admin/deals", "deals"], ["/admin/reviews", "reviews"], ["/admin/community", "community_posts"], ["/admin/community-reports", "community_reports"], ["/admin/pickup-locations", "pickup_locations"], ["/admin/pickup-slots", "pickup_slots"], ["/admin/audit-logs", "audit_logs"], ["/admin/auctions", "auction_items"]] as const) {
  adminRouter.get(path, adminOnly, async (context) => { const { data, error } = await getAdminSupabase().from(table).select("*").order("created_at", { ascending: false }).limit(200); return error ? context.json(apiFailure("QUERY_FAILED", `${table} 목록을 조회하지 못했습니다.`), 502) : context.json(apiSuccess({ items: data ?? [] })); });
}
adminRouter.patch("/admin/products/:id", adminOnly, async (context) => {
  const parsed = z.object({ status: z.enum(["active", "rejected", "hidden"]), reason: reasonSchema }).strict().safeParse(await context.req.json().catch(() => null)); if (!parsed.success) return context.json(apiFailure("INVALID_INPUT", "상품 처리 상태를 확인하세요."), 400);
  const supabase = getAdminSupabase(); const before = await supabase.from("products").select("*").eq("id", context.req.param("id")).maybeSingle(); if (!before.data) return context.json(apiFailure("NOT_FOUND", "상품을 찾을 수 없습니다."), 404); const { data, error } = await supabase.from("products").update({ status: parsed.data.status, rejection_reason: parsed.data.status === "rejected" ? parsed.data.reason : null, updated_at: new Date().toISOString() }).eq("id", context.req.param("id")).select().single(); if (error) return context.json(apiFailure("SAVE_FAILED", "상품 상태를 변경하지 못했습니다."), 400); await audit(context.var.currentUser!.id, "product.moderate", "product", data.id, before.data, data, parsed.data.reason); return context.json(apiSuccess({ product: data }));
});
adminRouter.patch("/admin/deals/:id", adminOnly, async (context) => {
  const parsed = z.object({ status: z.enum(["draft", "active", "ended", "cancelled"]), reason: reasonSchema }).strict().safeParse(await context.req.json().catch(() => null)); if (!parsed.success) return context.json(apiFailure("INVALID_INPUT", "딜 처리 상태를 확인하세요."), 400);
  const supabase = getAdminSupabase(); const before = await supabase.from("deals").select("*").eq("id", context.req.param("id")).maybeSingle(); if (!before.data) return context.json(apiFailure("NOT_FOUND", "딜을 찾을 수 없습니다."), 404);
  const update = { status: parsed.data.status, ...(parsed.data.status === "ended" ? { ends_at: new Date().toISOString() } : {}), updated_at: new Date().toISOString() }; const { data, error } = await supabase.from("deals").update(update).eq("id", context.req.param("id")).select().single();
  if (error) return context.json(apiFailure("SAVE_FAILED", "딜 상태를 변경하지 못했습니다."), 400); await audit(context.var.currentUser!.id, "deal.moderate", "deal", data.id, before.data, data, parsed.data.reason); return context.json(apiSuccess({ deal: data }));
});
adminRouter.patch("/admin/moderation/:resource/:id", adminOnly, async (context) => {
  const resource = context.req.param("resource"); const tableMap: Record<string, { table: string; statuses: string[] }> = { reviews: { table: "reviews", statuses: ["visible", "hidden"] }, community: { table: "community_posts", statuses: ["visible", "hidden"] }, reports: { table: "community_reports", statuses: ["open", "resolved", "dismissed"] } }; const target = tableMap[resource]; if (!target) return context.json(apiFailure("INVALID_RESOURCE", "지원하지 않는 관리 대상입니다."), 400);
  const parsed = z.object({ status: z.string().min(2).max(30), reason: reasonSchema }).strict().safeParse(await context.req.json().catch(() => null)); if (!parsed.success || !target.statuses.includes(parsed.data.status)) return context.json(apiFailure("INVALID_INPUT", "처리 상태와 사유를 확인하세요."), 400);
  const supabase = getAdminSupabase(); const before = await supabase.from(target.table).select("*").eq("id", context.req.param("id")).maybeSingle(); if (!before.data) return context.json(apiFailure("NOT_FOUND", "관리 대상을 찾을 수 없습니다."), 404); const { data, error } = await supabase.from(target.table).update({ status: parsed.data.status, updated_at: new Date().toISOString() }).eq("id", context.req.param("id")).select().single(); if (error) return context.json(apiFailure("SAVE_FAILED", "관리 상태를 변경하지 못했습니다."), 400); await audit(context.var.currentUser!.id, `${resource}.moderate`, resource, context.req.param("id"), before.data, data, parsed.data.reason); return context.json(apiSuccess({ item: data }));
});

const locationInput = z.object({ name: z.string().min(2).max(120), address: z.string().min(5).max(300), description: z.string().max(500).default("") }).strict();
const locationPatch = z.object({ name: z.string().min(2).max(120).optional(), address: z.string().min(5).max(300).optional(), description: z.string().max(500).optional(), isActive: z.boolean().optional(), reason: reasonSchema }).strict();
const slotInput = z.object({ locationId: z.string().uuid(), pickupDate: z.string().date(), startTime: z.string().regex(/^\d{2}:\d{2}$/), endTime: z.string().regex(/^\d{2}:\d{2}$/), pickupAt: z.string().datetime(), capacity: z.number().int().positive().max(100000) }).strict();
const slotPatch = z.object({ locationId: z.string().uuid().optional(), pickupDate: z.string().date().optional(), startTime: z.string().regex(/^\d{2}:\d{2}$/).optional(), endTime: z.string().regex(/^\d{2}:\d{2}$/).optional(), pickupAt: z.string().datetime().optional(), capacity: z.number().int().positive().max(100000).optional(), isActive: z.boolean().optional(), reason: reasonSchema }).strict();
adminRouter.post("/admin/pickup-locations", adminOnly, async (context) => {
  const parsed = locationInput.safeParse(await context.req.json().catch(() => null)); if (!parsed.success) return context.json(apiFailure("INVALID_INPUT", "픽업 장소를 확인하세요."), 400); const { data, error } = await getAdminSupabase().from("pickup_locations").insert(parsed.data).select().single(); return error ? context.json(apiFailure("SAVE_FAILED", "장소를 저장하지 못했습니다."), 400) : context.json(apiSuccess({ location: data }), 201);
});
adminRouter.patch("/admin/pickup-locations/:id", adminOnly, async (context) => {
  const parsed = locationPatch.safeParse(await context.req.json().catch(() => null)); if (!parsed.success) return context.json(apiFailure("INVALID_INPUT", "픽업 장소 변경 정보를 확인하세요."), 400); const supabase = getAdminSupabase(); const before = await supabase.from("pickup_locations").select("*").eq("id", context.req.param("id")).maybeSingle(); if (!before.data) return context.json(apiFailure("NOT_FOUND", "장소를 찾을 수 없습니다."), 404);
  const update = { ...(parsed.data.name ? { name: parsed.data.name } : {}), ...(parsed.data.address ? { address: parsed.data.address } : {}), ...(parsed.data.description !== undefined ? { description: parsed.data.description } : {}), ...(parsed.data.isActive !== undefined ? { is_active: parsed.data.isActive } : {}), updated_at: new Date().toISOString() }; const { data, error } = await supabase.from("pickup_locations").update(update).eq("id", context.req.param("id")).select().single(); if (error) return context.json(apiFailure("SAVE_FAILED", "장소를 변경하지 못했습니다."), 400); await audit(context.var.currentUser!.id, "pickup_location.update", "pickup_location", data.id, before.data, data, parsed.data.reason); return context.json(apiSuccess({ location: data }));
});
adminRouter.delete("/admin/pickup-locations/:id", adminOnly, async (context) => {
  const parsed = z.object({ reason: reasonSchema }).strict().safeParse(await context.req.json().catch(() => null)); if (!parsed.success) return context.json(apiFailure("INVALID_INPUT", "운영 종료 사유를 확인하세요."), 400); const supabase = getAdminSupabase(); const before = await supabase.from("pickup_locations").select("*").eq("id", context.req.param("id")).maybeSingle(); if (!before.data) return context.json(apiFailure("NOT_FOUND", "장소를 찾을 수 없습니다."), 404); await supabase.from("pickup_slots").update({ is_active: false }).eq("location_id", before.data.id); const { data, error } = await supabase.from("pickup_locations").update({ is_active: false, updated_at: new Date().toISOString() }).eq("id", before.data.id).select().single(); if (error) return context.json(apiFailure("SAVE_FAILED", "장소 운영을 종료하지 못했습니다."), 400); await audit(context.var.currentUser!.id, "pickup_location.close", "pickup_location", data.id, before.data, data, parsed.data.reason); return context.json(apiSuccess({ location: data }));
});
adminRouter.post("/admin/pickup-slots", adminOnly, async (context) => {
  const parsed = slotInput.safeParse(await context.req.json().catch(() => null)); if (!parsed.success) return context.json(apiFailure("INVALID_INPUT", "픽업 슬롯을 확인하세요."), 400); const { data, error } = await getAdminSupabase().from("pickup_slots").insert({ location_id: parsed.data.locationId, pickup_date: parsed.data.pickupDate, start_time: parsed.data.startTime, end_time: parsed.data.endTime, pickup_at: parsed.data.pickupAt, capacity: parsed.data.capacity }).select().single(); return error ? context.json(apiFailure("SAVE_FAILED", "슬롯을 저장하지 못했습니다."), 400) : context.json(apiSuccess({ slot: data }), 201);
});
adminRouter.patch("/admin/pickup-slots/:id", adminOnly, async (context) => {
  const parsed = slotPatch.safeParse(await context.req.json().catch(() => null)); if (!parsed.success) return context.json(apiFailure("INVALID_INPUT", "픽업 슬롯 변경 정보를 확인하세요."), 400); const supabase = getAdminSupabase(); const before = await supabase.from("pickup_slots").select("*").eq("id", context.req.param("id")).maybeSingle(); if (!before.data) return context.json(apiFailure("NOT_FOUND", "슬롯을 찾을 수 없습니다."), 404); if (parsed.data.capacity !== undefined && parsed.data.capacity < Number(before.data.reserved_count)) return context.json(apiFailure("CAPACITY_CONFLICT", "예약 인원보다 정원을 줄일 수 없습니다."), 409);
  const update = { ...(parsed.data.locationId ? { location_id: parsed.data.locationId } : {}), ...(parsed.data.pickupDate ? { pickup_date: parsed.data.pickupDate } : {}), ...(parsed.data.startTime ? { start_time: parsed.data.startTime } : {}), ...(parsed.data.endTime ? { end_time: parsed.data.endTime } : {}), ...(parsed.data.pickupAt ? { pickup_at: parsed.data.pickupAt } : {}), ...(parsed.data.capacity !== undefined ? { capacity: parsed.data.capacity } : {}), ...(parsed.data.isActive !== undefined ? { is_active: parsed.data.isActive } : {}) }; const { data, error } = await supabase.from("pickup_slots").update(update).eq("id", context.req.param("id")).select().single(); if (error) return context.json(apiFailure("SAVE_FAILED", "슬롯을 변경하지 못했습니다."), 400); await audit(context.var.currentUser!.id, "pickup_slot.update", "pickup_slot", data.id, before.data, data, parsed.data.reason); return context.json(apiSuccess({ slot: data }));
});
adminRouter.delete("/admin/pickup-slots/:id", adminOnly, async (context) => {
  const parsed = z.object({ reason: reasonSchema }).strict().safeParse(await context.req.json().catch(() => null)); if (!parsed.success) return context.json(apiFailure("INVALID_INPUT", "운영 종료 사유를 확인하세요."), 400); const supabase = getAdminSupabase(); const before = await supabase.from("pickup_slots").select("*").eq("id", context.req.param("id")).maybeSingle(); if (!before.data) return context.json(apiFailure("NOT_FOUND", "슬롯을 찾을 수 없습니다."), 404); const { data, error } = await supabase.from("pickup_slots").update({ is_active: false }).eq("id", before.data.id).select().single(); if (error) return context.json(apiFailure("SAVE_FAILED", "슬롯 운영을 종료하지 못했습니다."), 400); await audit(context.var.currentUser!.id, "pickup_slot.close", "pickup_slot", data.id, before.data, data, parsed.data.reason); return context.json(apiSuccess({ slot: data }));
});
adminRouter.delete("/admin/auctions/:id", adminOnly, async (context) => {
  const parsed = z.object({ reason: reasonSchema }).strict().safeParse(await context.req.json().catch(() => null)); if (!parsed.success) return context.json(apiFailure("INVALID_INPUT", "삭제 사유를 확인하세요."), 400);
  const supabase = getAdminSupabase(); const before = await supabase.from("auction_items").select("*").eq("id", context.req.param("id")).maybeSingle(); if (!before.data) return context.json(apiFailure("NOT_FOUND", "경매를 찾을 수 없습니다."), 404);
  const { error } = await supabase.from("auction_items").delete().eq("id", before.data.id); if (error) return context.json(apiFailure("DELETE_FAILED", "경매를 삭제하지 못했습니다."), 400);
  await audit(context.var.currentUser!.id, "auction.delete", "auction_item", before.data.id, before.data, null, parsed.data.reason); return context.json(apiSuccess({ deleted: true }));
});
adminRouter.get("/admin-research", adminOnly, async (context) => { const { data, error } = await getAdminSupabase().from("products").select("category,regular_price,status"); if (error) return context.json(apiFailure("QUERY_FAILED", "통계를 생성하지 못했습니다."), 502); const groups = new Map<string, number[]>(); for (const item of data ?? []) { const prices = groups.get(item.category) ?? []; prices.push(item.regular_price); groups.set(item.category, prices); } return context.json(apiSuccess({ research: { generatedAt: new Date().toISOString(), source: "supabase_snapshot", categories: [...groups].map(([category, prices]) => ({ category, productCount: prices.length, averagePrice: Math.round(prices.reduce((sum, price) => sum + price, 0) / prices.length) })) } })); });
