/**
 * 회원가입·로그인·로그아웃·세션 확인·비밀번호 찾기 API를 제공합니다.
 * 프론트 AuthPage와 authClient가 `/api/auth/*` 경로로 이 모듈을 사용합니다.
 * Supabase Auth 토큰과 profiles 역할을 결합하되 service role key는 응답하지 않습니다.
 */
import {Hono} from "hono"; import {z} from "zod"; import {apiFailure,apiSuccess} from "../../http.js"; import {getAdminSupabase,getAnonSupabase} from "../../supabase.js"; import {requireAuth} from "../../middleware/auth.js"; import {config} from "../../config.js";
export const authRouter=new Hono(); const credentials=z.object({email:z.string().email(),password:z.string().min(8)});
const userView=(u:any,p?:any)=>({id:u.id,email:u.email??"",name:p?.name??u.user_metadata?.name??"사용자",emailVerified:Boolean(u.email_confirmed_at),role:p?.role??"user"});
authRouter.post("/sign-up",async c=>{const parsed=credentials.extend({name:z.string().min(2).max(50)}).safeParse(await c.req.json().catch(()=>null)); if(!parsed.success)return c.json(apiFailure("INVALID_INPUT","회원가입 입력값을 확인하세요.",parsed.error.flatten()),400); try{const sb=getAnonSupabase(); const {data,error}=await sb.auth.signUp({email:parsed.data.email,password:parsed.data.password,options:{data:{name:parsed.data.name}}}); if(error||!data.user)return c.json(apiFailure("SIGNUP_FAILED",error?.message??"회원가입 실패"),400); if(data.session){await getAdminSupabase().from("profiles").upsert({id:data.user.id,name:parsed.data.name,role:"user"});} return c.json(apiSuccess({accessToken:data.session?.access_token??null,user:userView(data.user,{name:parsed.data.name})}),201)}catch{return c.json(apiFailure("SUPABASE_UNCONFIGURED","Supabase 환경변수를 설정하세요."),503)}});
authRouter.post("/sign-in",async c=>{const parsed=credentials.safeParse(await c.req.json().catch(()=>null)); if(!parsed.success)return c.json(apiFailure("INVALID_INPUT","이메일과 비밀번호를 확인하세요."),400); try{const sb=getAnonSupabase();const {data,error}=await sb.auth.signInWithPassword(parsed.data);if(error||!data.user||!data.session)return c.json(apiFailure("SIGNIN_FAILED",error?.message??"로그인 실패"),401);const {data:p}=await getAdminSupabase().from("profiles").select("name,role").eq("id",data.user.id).maybeSingle();return c.json(apiSuccess({accessToken:data.session.access_token,user:userView(data.user,p)}))}catch{return c.json(apiFailure("SUPABASE_UNCONFIGURED","Supabase 환경변수를 설정하세요."),503)}});
authRouter.get("/session",requireAuth,c=>c.json(apiSuccess({accessToken:null,user:c.var.currentUser})));
authRouter.post("/sign-out",requireAuth,c=>c.json(apiSuccess({signedOut:true})));
authRouter.post("/forgot-password",async c=>{const parsed=z.object({email:z.string().email(),redirectTo:z.string().url().optional()}).safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return c.json(apiFailure("INVALID_INPUT","이메일을 확인하세요."),400);try{const {error}=await getAnonSupabase().auth.resetPasswordForEmail(parsed.data.email,{redirectTo:parsed.data.redirectTo??`${config.publicBackendUrl}/auth`});if(error)return c.json(apiFailure("RESET_FAILED",error.message),400);return c.json(apiSuccess({sent:true}))}catch{return c.json(apiFailure("SUPABASE_UNCONFIGURED","Supabase 환경변수를 설정하세요."),503)}});
