/**
 * 상품 목록·상세와 타임딜 목록·상세 공개 조회 API를 제공합니다.
 * Products 페이지와 Home이 `/catalog`, `/deals` 결과를 조합해 사용합니다.
 * Supabase 미연결 시 공개 읽기만 source sample 표시와 함께 폴백합니다.
 */
import{Hono}from"hono";import{apiFailure,apiSuccess}from"../../http.js";import{isSupabaseConfigured}from"../../config.js";import{getAdminSupabase}from"../../supabase.js";import{sampleDeals,sampleProducts}from"../../sample.js";
export const catalogRouter=new Hono();
catalogRouter.get("/catalog",async c=>{if(!isSupabaseConfigured())return c.json(apiSuccess({catalog:sampleProducts,source:"sample",notice:"샘플 폴백: Supabase 미연결 상태이며 운영 데이터가 아닙니다."}));const{data,error}=await getAdminSupabase().from("products").select("id,name,description,category,image,regular_price,status,inventory").eq("status","active");if(error)return c.json(apiFailure("QUERY_FAILED",error.message),502);return c.json(apiSuccess({catalog:(data??[]).map((p:any)=>({...p,regularPrice:p.regular_price})),source:"supabase"}))});
catalogRouter.get("/catalog/:id",async c=>{const id=c.req.param("id");if(!isSupabaseConfigured()){const p=sampleProducts.find(x=>x.id===id);return p?c.json(apiSuccess({product:p,source:"sample",notice:"샘플 폴백 데이터"})):c.json(apiFailure("NOT_FOUND","상품을 찾을 수 없습니다."),404)}const{data,error}=await getAdminSupabase().from("products").select("*").eq("id",id).eq("status","active").maybeSingle();if(error)return c.json(apiFailure("QUERY_FAILED",error.message),502);return data?c.json(apiSuccess({product:data,source:"supabase"})):c.json(apiFailure("NOT_FOUND","상품을 찾을 수 없습니다."),404)});
catalogRouter.get("/deals",async c=>{if(!isSupabaseConfigured())return c.json(apiSuccess({deals:sampleDeals,source:"sample",notice:"샘플 폴백: Supabase 미연결 상태이며 운영 데이터가 아닙니다."}));const{data,error}=await getAdminSupabase().from("deals").select("*,product:products(*)").eq("status","active");if(error)return c.json(apiFailure("QUERY_FAILED",error.message),502);return c.json(apiSuccess({deals:(data??[]).map((d:any)=>({...d,productId:d.product_id,dealPrice:d.deal_price,startsAt:d.starts_at,endsAt:d.ends_at,progress:Math.round(d.participants/d.target*100),product:d.product?{...d.product,regularPrice:d.product.regular_price}:null})),source:"supabase"}))});
catalogRouter.get("/deals/:id",async c=>{if(!isSupabaseConfigured()){const d=sampleDeals.find(x=>x.id===c.req.param("id"));return d?c.json(apiSuccess({deal:d,source:"sample"})):c.json(apiFailure("NOT_FOUND","딜을 찾을 수 없습니다."),404)}const{data,error}=await getAdminSupabase().from("deals").select("*,product:products(*)").eq("id",c.req.param("id")).maybeSingle();if(error)return c.json(apiFailure("QUERY_FAILED",error.message),502);return data?c.json(apiSuccess({deal:data,source:"supabase"})):c.json(apiFailure("NOT_FOUND","딜을 찾을 수 없습니다."),404)});
