-- 타임딜 운영에 필요한 프로필·상품·딜·참여·문의·리뷰·커뮤니티 테이블을 생성합니다.
-- Auth와 각 기능 모듈이 사용하는 trigger, 역할 타입, RLS 정책까지 Supabase에 구성합니다.
-- Supabase SQL Editor에서 seed.sql보다 먼저 한 번 실행합니다.
create extension if not exists pgcrypto;
create type public.app_role as enum ('user','seller','admin');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null default '사용자', role public.app_role not null default 'user', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.products (id text primary key default gen_random_uuid()::text, seller_id uuid references public.profiles(id) on delete set null, name text not null, description text not null, category text not null, image text not null, regular_price integer not null check(regular_price>=0), inventory integer not null default 0 check(inventory>=0), status text not null default 'draft' check(status in('draft','active','hidden')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.deals (id text primary key default gen_random_uuid()::text, product_id text not null references public.products(id) on delete cascade, deal_price integer not null check(deal_price>=0), participants integer not null default 0, target integer not null check(target>0), starts_at timestamptz not null, ends_at timestamptz not null, status text not null default 'active' check(status in('draft','active','ended','cancelled')), created_at timestamptz not null default now());
create table public.participations (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, deal_id text not null references public.deals(id) on delete cascade, quantity integer not null check(quantity between 1 and 20), status text not null default 'joined', created_at timestamptz not null default now());
create table public.inquiries (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, product_id text references public.products(id) on delete set null, audience text not null check(audience in('customer','seller')), subject text not null, message text not null, status text not null default 'open', created_at timestamptz not null default now());
create table public.reviews (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, product_id text not null references public.products(id) on delete cascade, rating integer not null check(rating between 1 and 5), content text not null, created_at timestamptz not null default now());
create table public.community_posts (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, title text not null, content text not null, purchase_intent boolean not null default false, status text not null default 'visible', created_at timestamptz not null default now());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,name) values(new.id,coalesce(new.raw_user_meta_data->>'name','사용자')) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
alter table public.profiles enable row level security; alter table public.products enable row level security; alter table public.deals enable row level security; alter table public.participations enable row level security; alter table public.inquiries enable row level security; alter table public.reviews enable row level security; alter table public.community_posts enable row level security;
create policy "public active products" on public.products for select using(status='active'); create policy "public active deals" on public.deals for select using(status='active'); create policy "public visible community" on public.community_posts for select using(status='visible'); create policy "own profile read" on public.profiles for select using(auth.uid()=id); create policy "own participation" on public.participations for all using(auth.uid()=user_id) with check(auth.uid()=user_id); create policy "own inquiries" on public.inquiries for all using(auth.uid()=user_id) with check(auth.uid()=user_id); create policy "own reviews" on public.reviews for all using(auth.uid()=user_id) with check(auth.uid()=user_id); create policy "own posts write" on public.community_posts for insert with check(auth.uid()=user_id);
